# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTextField' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyTextField

pod 'YYKit', '~> 1.0.5'
pod 'Masonry', '~> 1.0.1'

  target 'MyTextFieldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyTextFieldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
